[package]
name = "gitm"
version = "0.1.0"
edition = "2021"

[dependencies]
clier_parser = "0.7.4"
clier = "0.7.1"
url = "2.5.0"
serde = {version = "1.0.202", features = ["derive"]}
serde_json = "1.0.117"
