[package]
name = "gitm"
description = "Git manager is a nice wrapper to git, where it manages repos in a specified directory"
license = "MIT"
version = "0.3.0"
edition = "2021"

[dependencies]
clier = "0.7.2"
serde = {version = "1.0.202", features = ["derive"]}
serde_json = "1.0.117"
